CREATE TABLE invoices (
    invoice_id INT PRIMARY KEY,
    payment_total DECIMAL(8,2),
    payment_date DATE,
    client_id INT,
    invoice_total DECIMAL(8,2)
);

CREATE TABLE ExchangeRates (
  id INT PRIMARY KEY,
  currencyCode VARCHAR(10),
  exchangeRate DECIMAL(10, 2),
  effectiveDate DATE,
  expirationDate DATE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CurrencyCodes (
  id INT PRIMARY KEY,
  currencyCode VARCHAR(10),
  currencyName VARCHAR(50),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DBV_PARAM_TDM_TDG_IND (
  id INT PRIMARY KEY,
  dbvParamTdmTdgInd VARCHAR(50),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DiaryEvents (
  id INT PRIMARY KEY,
  diaryEventId VARCHAR(50),
  diaryEventDate DATE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Transactions (
  id INT PRIMARY KEY,
  transactionType VARCHAR(50),
  transactionDate DATE,
  transactionAmount DECIMAL(10, 2),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TransactionData (
  id INT PRIMARY KEY,
  transactionId INT,
  column1 VARCHAR(50),
  column2 VARCHAR(50),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (transactionId) REFERENCES Transactions(id)
);

CREATE TABLE Messages (
  id INT PRIMARY KEY,
  messageType VARCHAR(10),
  messageText VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MessageTags (
  id INT PRIMARY KEY,
  messageId INT,
  tag VARCHAR(10),
  tagValue VARCHAR(50),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (messageId) REFERENCES Messages(id)
);

INSERT INTO invoices (invoice_id, payment_total, payment_date, client_id, invoice_total) VALUES
(1, 0, '2022-01-01', 1, 100),
(2, 0, '2022-02-01', 1, 200),
(3, 0, '2022-03-01', 2, 300),
(4, 0, '2022-04-01', 2, 400),
(5, 0, '2022-05-01', 3, 500);

CREATE TABLE SystemData (
  id INT PRIMARY KEY,
  column1 VARCHAR(50),
  column2 VARCHAR(50),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OutputMessages (
  id INT PRIMARY KEY,
  outputMessageId VARCHAR(50),
  outputMessageText VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TRANSACTION (
  TRANSACTION_ID INT PRIMARY KEY,
  TRANSACTION_TYPE VARCHAR(20),
  TRANSACTION_DATE DATE,
  TRANSACTION_TIME TIME,
  CREATED_BY VARCHAR(50),
  CREATED_ON TIMESTAMP
);

CREATE TABLE SECURITY (
  SECURITY_ID INT PRIMARY KEY,
  SECURITY_TYPE VARCHAR(20),
  SECURITY_NAME VARCHAR(100),
  ISIN VARCHAR(20),
  CREATED_BY VARCHAR(50),
  CREATED_ON TIMESTAMP
);

CREATE TABLE STOCK_MOVEMENT (
  STOCK_MOVEMENT_ID INT PRIMARY KEY,
  TRANSACTION_ID INT,
  SECURITY_ID INT,
  MOVEMENT_TYPE VARCHAR(20),
  QUANTITY DECIMAL(10, 2),
  CREATED_BY VARCHAR(50),
  CREATED_ON TIMESTAMP,
  FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION(TRANSACTION_ID),
  FOREIGN KEY (SECURITY_ID) REFERENCES SECURITY(SECURITY_ID)
);

CREATE TABLE PARTICIPANT (
  PARTICIPANT_ID INT PRIMARY KEY,
  PARTICIPANT_NAME VARCHAR(100),
  PARTICIPANT_TYPE VARCHAR(20),
  CREATED_BY VARCHAR(50),
  CREATED_ON TIMESTAMP
);

CREATE TABLE PARTICIPANT_TRANSACTION (
  PARTICIPANT_TRANSACTION_ID INT PRIMARY KEY,
  PARTICIPANT_ID INT,
  TRANSACTION_ID INT,
  TRANSACTION_TYPE VARCHAR(20),
  CREATED_BY VARCHAR(50),
  CREATED_ON TIMESTAMP,
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANT(PARTICIPANT_ID),
  FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION(TRANSACTION_ID)
);

CREATE TABLE CASH_MOVEMENT (
  CASH_MOVEMENT_ID INT PRIMARY KEY,
  TRANSACTION_ID INT,
  CASH_TYPE VARCHAR(20),
  AMOUNT DECIMAL(10, 2),
  CREATED_BY VARCHAR(50),
  CREATED_ON TIMESTAMP,
  FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION(TRANSACTION_ID)
);

CREATE TABLE SETTLEMENT_PARAMS (
  SETTLEMENT_PARAM_ID INT PRIMARY KEY,
  PRE_FUND_STATUS VARCHAR(20),
  LEAST_HIGH_PRIORITY VARCHAR(20),
  REPO_PURCHASE_FLOOR DECIMAL(10, 2),
  REPO_SALE_FLOOR DECIMAL(10, 2),
  REPO_CCY VARCHAR(20),
  GILTS_MMI_DAY VARCHAR(20),
  REPO_STOCK_VALUE_FLOOR DECIMAL(10, 2),
  CREATED_BY VARCHAR(50),
  CREATED_ON TIMESTAMP
);