name: Agentic MCP Pipeline


on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  create-pr-and-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
