name: Automated Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run code review agent
        run: |
          echo "Running code review agent..."
          python3 .github/scripts/code_review_agent.py
      - name: Upload review results
        uses: actions/upload-artifact@v4
        with:
          name: code-review-results
          path: code-review-results.txt
